### PR TITLE
Bugfix/45 empty pullrequests dropdown

### PR DESCRIPTION
**Pull request by ra100**
Loads atlassian web resources for pull-requests only on pr list page.

### CODE REVIEW

**Comment by mrvincenzo** [comment]
@ra100 @dragouf @PavelVanecek Any ETA on when it will be merged? It is kind of a showstopper.

**Comment by ra100** [comment]
@mrvincenzo I'm sorry, I don't have permissions to merge nor publish to chrome store.

**Comment by mrvincenzo** [comment]
@dragouf Any ETA on merging this PR and releasing a build?

**Comment by ra100** [comment]
I took the liberty to add to this PR changes from @stellarashes

**Pull request merged**
